package kp.beans.user.pojo;
// Generated Nov 10, 2015 7:53:17 AM by Hibernate Tools 4.3.1


import java.util.HashSet;
import java.util.Set;

/**
 * MocUserRoleMst generated by hbm2java
 */
public class MocUserRoleMst  implements java.io.Serializable {


     private String roleId;
     private String roleName;
     private String roleType;
     private Set mocWfStgRoles = new HashSet(0);
     private Set mocUserRoleDts = new HashSet(0);

    public MocUserRoleMst() {
    }

	
    public MocUserRoleMst(String roleId) {
        this.roleId = roleId;
    }
    public MocUserRoleMst(String roleId, String roleName, String roleType, Set mocWfStgRoles, Set mocUserRoleDts) {
       this.roleId = roleId;
       this.roleName = roleName;
       this.roleType = roleType;
       this.mocWfStgRoles = mocWfStgRoles;
       this.mocUserRoleDts = mocUserRoleDts;
    }
   
    public String getRoleId() {
        return this.roleId;
    }
    
    public void setRoleId(String roleId) {
        this.roleId = roleId;
    }
    public String getRoleName() {
        return this.roleName;
    }
    
    public void setRoleName(String roleName) {
        this.roleName = roleName;
    }
    public String getRoleType() {
        return this.roleType;
    }
    
    public void setRoleType(String roleType) {
        this.roleType = roleType;
    }
    public Set getMocWfStgRoles() {
        return this.mocWfStgRoles;
    }
    
    public void setMocWfStgRoles(Set mocWfStgRoles) {
        this.mocWfStgRoles = mocWfStgRoles;
    }
    public Set getMocUserRoleDts() {
        return this.mocUserRoleDts;
    }
    
    public void setMocUserRoleDts(Set mocUserRoleDts) {
        this.mocUserRoleDts = mocUserRoleDts;
    }




}


