package kp.beans.user.pojo;
// Generated Nov 10, 2015 7:53:17 AM by Hibernate Tools 4.3.1

import java.util.Date;
import java.util.HashSet;
import java.util.Set;

/**
 * MocUserMst generated by hbm2java
 */
public class MocUserMst implements java.io.Serializable {

    private String userId;
    private String userName;
    private String emailId;
    private String unit;
    private String dept;
    private String userType;
    private Character isActive;
    private Date creationDate;
    private Date updatedDate;
    private MocUserPass mocUserPass;

    private Set mocWfAtts = new HashSet(0);
    private Set mocUserRoleDts = new HashSet(0);
    private Set mocUserLoginHistories = new HashSet(0);

    public MocUserMst() {
    }

    public MocUserMst(String userId) {
        this.userId = userId;
    }

    public MocUserMst(String userId, String userName, String emailId, String unit,
            String dept, String userType, Character isActive, Date creationDate, Date updatedDate,
            MocUserPass mocUserPass, Set mocWfAtts, Set mocUserRoleDts, Set mocUserLoginHistories) {
        this.userId = userId;
        this.userName = userName;
        this.emailId = emailId;
        this.unit = unit;
        this.dept = dept;
        this.userType = userType;
        this.isActive = isActive;
        this.creationDate = creationDate;
        this.updatedDate = updatedDate;
        this.mocUserPass = mocUserPass;
        this.mocWfAtts = mocWfAtts;
        this.mocUserRoleDts = mocUserRoleDts;
        this.mocUserLoginHistories = mocUserLoginHistories;
    }

    public String getUserId() {
        return this.userId;
    }

    public void setUserId(String userId) {
        this.userId = userId;
    }

    public String getUserName() {
        return this.userName;
    }

    public void setUserName(String userName) {
        this.userName = userName;
    }

    public String getEmailId() {
        return this.emailId;
    }

    public void setEmailId(String emailId) {
        this.emailId = emailId;
    }

    public String getUnit() {
        return this.unit;
    }

    public void setUnit(String unit) {
        this.unit = unit;
    }

    public String getDept() {
        return this.dept;
    }

    public void setDept(String dept) {
        this.dept = dept;
    }

    public String getUserType() {
        return this.userType;
    }

    public void setUserType(String userType) {
        this.userType = userType;
    }

    public Character getIsActive() {
        return this.isActive;
    }

    public void setIsActive(Character isActive) {
        this.isActive = isActive;
    }

    public Date getCreationDate() {
        return this.creationDate;
    }

    public void setCreationDate(Date creationDate) {
        this.creationDate = creationDate;
    }

    public Date getUpdatedDate() {
        return this.updatedDate;
    }

    public void setUpdatedDate(Date updatedDate) {
        this.updatedDate = updatedDate;
    }

    public Set getMocWfAtts() {
        return this.mocWfAtts;
    }

    public void setMocWfAtts(Set mocWfAtts) {
        this.mocWfAtts = mocWfAtts;
    }

    public Set getMocUserRoleDts() {
        return this.mocUserRoleDts;
    }

    public void setMocUserRoleDts(Set mocUserRoleDts) {
        this.mocUserRoleDts = mocUserRoleDts;
    }

    public Set getMocUserLoginHistories() {
        return this.mocUserLoginHistories;
    }

    public void setMocUserLoginHistories(Set mocUserLoginHistories) {
        this.mocUserLoginHistories = mocUserLoginHistories;
    }

    /**
     * @return the mocUserPass
     */
    public MocUserPass getMocUserPass() {
        return mocUserPass;
    }

    /**
     * @param mocUserPass the mocUserPass to set
     */
    public void setMocUserPass(MocUserPass mocUserPass) {
        this.mocUserPass = mocUserPass;
    }

}
