package kp.beans.user.pojo;
// Generated Nov 10, 2015 7:53:17 AM by Hibernate Tools 4.3.1

import java.util.Date;

/**
 * MocUserLoginHistory generated by hbm2java
 */
public class MocUserLoginHistory implements java.io.Serializable {

    private int id;
    private MocUserMst mocUserMst;
    private Date loginTime;
    private Date logoutTime;

    public MocUserLoginHistory() {
    }

    public MocUserLoginHistory(int id) {
        this.id = id;
    }

    public MocUserLoginHistory(int id, MocUserMst mocUserMst, Date loginTime, Date logoutTime) {
        this.id = id;
        this.mocUserMst = mocUserMst;
        this.loginTime = loginTime;
        this.logoutTime = logoutTime;
    }

    public int getId() {
        return this.id;
    }

    public void setId(int id) {
        this.id = id;
    }

    public MocUserMst getMocUserMst() {
        return this.mocUserMst;
    }

    public void setMocUserMst(MocUserMst mocUserMst) {
        this.mocUserMst = mocUserMst;
    }

    public Date getLoginTime() {
        return this.loginTime;
    }

    public void setLoginTime(Date loginTime) {
        this.loginTime = loginTime;
    }

    public Date getLogoutTime() {
        return this.logoutTime;
    }

    public void setLogoutTime(Date logoutTime) {
        this.logoutTime = logoutTime;
    }

}
