package kp.beans.user.pojo;
// Generated Nov 10, 2015 7:53:17 AM by Hibernate Tools 4.3.1

import java.util.Date;

/**
 * MocUserPass generated by hbm2java
 */
public class MocUserPass implements java.io.Serializable {

    private String userId;
    private MocUserMst mocUserMst;
    private String password;
    private Date effDate;

    public MocUserPass() {
    }

    public MocUserPass(String userId, MocUserMst mocUserMst) {
        this.userId = userId;
        this.mocUserMst = mocUserMst;
    }

    public MocUserPass(String userId, MocUserMst mocUserMst, String password, Date effDate) {
        this.userId = userId;
        this.mocUserMst = mocUserMst;
        this.password = password;
        this.effDate = effDate;
    }

    public MocUserMst getMocUserMst() {
        return this.mocUserMst;
    }

    public void setMocUserMst(MocUserMst mocUserMst) {
        this.mocUserMst = mocUserMst;
    }

    public String getPassword() {
        return this.password;
    }

    public void setPassword(String password) {
        this.password = password;
    }

    public Date getEffDate() {
        return this.effDate;
    }

    public void setEffDate(Date effDate) {
        this.effDate = effDate;
    }

    /**
     * @return the userId
     */
    public String getUserId() {
        return userId;
    }

    /**
     * @param userId the userId to set
     */
    public void setUserId(String userId) {
        this.userId = userId;
    }

}
