package kp.beans.user.pojo;
// Generated Nov 10, 2015 7:53:17 AM by Hibernate Tools 4.3.1




/**
 * MocUserRoleDt generated by hbm2java
 */
public class MocUserRoleDt  implements java.io.Serializable {


     private int id;
     private MocUserMst mocUserMst;
     private MocUserRoleMst mocUserRoleMst;
     private String group1;
     private String group2;

    public MocUserRoleDt() {
    }

	
    public MocUserRoleDt(int id, MocUserMst mocUserMst, MocUserRoleMst mocUserRoleMst) {
        this.id = id;
        this.mocUserMst = mocUserMst;
        this.mocUserRoleMst = mocUserRoleMst;
    }
    public MocUserRoleDt(int id, MocUserMst mocUserMst, MocUserRoleMst mocUserRoleMst, String group1, String group2) {
       this.id = id;
       this.mocUserMst = mocUserMst;
       this.mocUserRoleMst = mocUserRoleMst;
       this.group1 = group1;
       this.group2 = group2;
    }
   
    public int getId() {
        return this.id;
    }
    
    public void setId(int id) {
        this.id = id;
    }
    public MocUserMst getMocUserMst() {
        return this.mocUserMst;
    }
    
    public void setMocUserMst(MocUserMst mocUserMst) {
        this.mocUserMst = mocUserMst;
    }
    public MocUserRoleMst getMocUserRoleMst() {
        return this.mocUserRoleMst;
    }
    
    public void setMocUserRoleMst(MocUserRoleMst mocUserRoleMst) {
        this.mocUserRoleMst = mocUserRoleMst;
    }
    public String getGroup1() {
        return this.group1;
    }
    
    public void setGroup1(String group1) {
        this.group1 = group1;
    }
    public String getGroup2() {
        return this.group2;
    }
    
    public void setGroup2(String group2) {
        this.group2 = group2;
    }




}


