package kp.beans.wf.pojo;
// Generated Nov 10, 2015 7:53:17 AM by Hibernate Tools 4.3.1

import kp.beans.data.pojo.MocInitMst;


/**
 * MocWfUser generated by hbm2java
 */
public class MocWfUser implements java.io.Serializable {

    private int id;
    private MocInitMst mocInitMst;
    private int stgId;
    private String userId;

    public MocWfUser() {
    }

    public MocWfUser(int id) {
        this.id = id;
    }

    /**
     * @return the id
     */
    public int getId() {
        return id;
    }

    /**
     * @param id the id to set
     */
    public void setId(int id) {
        this.id = id;
    }

  

    /**
     * @return the stgId
     */
    public int getStgId() {
        return stgId;
    }

    /**
     * @param stgId the stgId to set
     */
    public void setStgId(int stgId) {
        this.stgId = stgId;
    }

    /**
     * @return the userId
     */
    public String getUserId() {
        return userId;
    }

    /**
     * @param userId the userId to set
     */
    public void setUserId(String userId) {
        this.userId = userId;
    }

    /**
     * @return the mocInitMst
     */
    public MocInitMst getMocInitMst() {
        return mocInitMst;
    }

    /**
     * @param mocInitMst the mocInitMst to set
     */
    public void setMocInitMst(MocInitMst mocInitMst) {
        this.mocInitMst = mocInitMst;
    }

}
