package kp.beans.wf.pojo;
// Generated Nov 10, 2015 7:53:17 AM by Hibernate Tools 4.3.1




/**
 * MocWfStgAct generated by hbm2java
 */
public class MocWfStgAct  implements java.io.Serializable {


     private int id;
     private MocWfStg mocWfStgByStgC;
     private MocWfStg mocWfStgByStgN;
     private String act;

    public MocWfStgAct() {
    }

	
    public MocWfStgAct(int id) {
        this.id = id;
    }
    public MocWfStgAct(int id, MocWfStg mocWfStgByStgC, MocWfStg mocWfStgByStgN, String act) {
       this.id = id;
       this.mocWfStgByStgC = mocWfStgByStgC;
       this.mocWfStgByStgN = mocWfStgByStgN;
       this.act = act;
    }
   
    public int getId() {
        return this.id;
    }
    
    public void setId(int id) {
        this.id = id;
    }
    public MocWfStg getMocWfStgByStgC() {
        return this.mocWfStgByStgC;
    }
    
    public void setMocWfStgByStgC(MocWfStg mocWfStgByStgC) {
        this.mocWfStgByStgC = mocWfStgByStgC;
    }
    public MocWfStg getMocWfStgByStgN() {
        return this.mocWfStgByStgN;
    }
    
    public void setMocWfStgByStgN(MocWfStg mocWfStgByStgN) {
        this.mocWfStgByStgN = mocWfStgByStgN;
    }
    public String getAct() {
        return this.act;
    }
    
    public void setAct(String act) {
        this.act = act;
    }




}


