package kp.beans.wf.pojo;
// Generated Nov 10, 2015 7:53:17 AM by Hibernate Tools 4.3.1



import java.util.HashSet;
import java.util.Set;

/**
 * MocWfStg generated by hbm2java
 */
public class MocWfStg  implements java.io.Serializable {


     private int stgId;
     private String stgName;
     private Set mocWfStgActsForStgC = new HashSet(0);
     private Set mocWfStgActsForStgN = new HashSet(0);
     private Set mocWfStgRoles = new HashSet(0);
     private Set mocWfUsers = new HashSet(0);

    public MocWfStg() {
    }

	
    public MocWfStg(int stgId) {
        this.stgId = stgId;
    }
    public MocWfStg(int stgId, String stgName, Set mocWfStgActsForStgC, Set mocWfStgActsForStgN, Set mocWfStgRoles, Set mocWfUsers) {
       this.stgId = stgId;
       this.stgName = stgName;
       this.mocWfStgActsForStgC = mocWfStgActsForStgC;
       this.mocWfStgActsForStgN = mocWfStgActsForStgN;
       this.mocWfStgRoles = mocWfStgRoles;
       this.mocWfUsers = mocWfUsers;
    }
   
    public int getStgId() {
        return this.stgId;
    }
    
    public void setStgId(int stgId) {
        this.stgId = stgId;
    }
    public String getStgName() {
        return this.stgName;
    }
    
    public void setStgName(String stgName) {
        this.stgName = stgName;
    }
    public Set getMocWfStgActsForStgC() {
        return this.mocWfStgActsForStgC;
    }
    
    public void setMocWfStgActsForStgC(Set mocWfStgActsForStgC) {
        this.mocWfStgActsForStgC = mocWfStgActsForStgC;
    }
    public Set getMocWfStgActsForStgN() {
        return this.mocWfStgActsForStgN;
    }
    
    public void setMocWfStgActsForStgN(Set mocWfStgActsForStgN) {
        this.mocWfStgActsForStgN = mocWfStgActsForStgN;
    }
    public Set getMocWfStgRoles() {
        return this.mocWfStgRoles;
    }
    
    public void setMocWfStgRoles(Set mocWfStgRoles) {
        this.mocWfStgRoles = mocWfStgRoles;
    }
    public Set getMocWfUsers() {
        return this.mocWfUsers;
    }
    
    public void setMocWfUsers(Set mocWfUsers) {
        this.mocWfUsers = mocWfUsers;
    }




}


