package kp.beans.wf.pojo;
// Generated Nov 10, 2015 7:53:17 AM by Hibernate Tools 4.3.1

import kp.beans.user.pojo.MocUserMst;
import java.util.Date;

/**
 * MocWfAtt generated by hbm2java
 */
public class MocWfAtt implements java.io.Serializable {

    private int id;
    private MocUserMst mocUserMst;
    private String userName;
    private int caseId;
    private String attType;
    private String FPath;
    private String FName;
    private Date actDate;
    private String actDateString;

    public MocWfAtt() {
    }

    public MocWfAtt(int id) {
        this.id = id;
    }

    public MocWfAtt(int id, MocUserMst mocUserMst, int caseId, String attType, String FPath, String FName, Date actDate) {
        this.id = id;
        this.mocUserMst = mocUserMst;
        this.caseId = caseId;
        this.attType = attType;
        this.FPath = FPath;
        this.FName = FName;
        this.actDate = actDate;
    }

    public int getId() {
        return this.id;
    }

    public void setId(int id) {
        this.id = id;
    }

    public MocUserMst getMocUserMst() {
        return this.mocUserMst;
    }

    public void setMocUserMst(MocUserMst mocUserMst) {
        this.mocUserMst = mocUserMst;
    }

    public int getCaseId() {
        return this.caseId;
    }

    public void setCaseId(int caseId) {
        this.caseId = caseId;
    }

    public String getAttType() {
        return this.attType;
    }

    public void setAttType(String attType) {
        this.attType = attType;
    }

    public String getFPath() {
        return this.FPath;
    }

    public void setFPath(String FPath) {
        this.FPath = FPath;
    }

    public String getFName() {
        return this.FName;
    }

    public void setFName(String FName) {
        this.FName = FName;
    }

    public Date getActDate() {
        return this.actDate;
    }

    public void setActDate(Date actDate) {
        this.actDate = actDate;
    }

    /**
     * @return the userName
     */
    public String getUserName() {
        return userName;
    }

    /**
     * @param userName the userName to set
     */
    public void setUserName(String userName) {
        this.userName = userName;
    }

    /**
     * @return the actDateString
     */
    public String getActDateString() {
        return actDateString;
    }

    /**
     * @param actDateString the actDateString to set
     */
    public void setActDateString(String actDateString) {
        this.actDateString = actDateString;
    }

}
