package kp.beans.wf.pojo;
// Generated Nov 10, 2015 7:53:17 AM by Hibernate Tools 4.3.1

import kp.beans.user.pojo.MocUserRoleMst;





/**
 * MocWfStgRole generated by hbm2java
 */
public class MocWfStgRole  implements java.io.Serializable {


     private int id;
     private MocUserRoleMst mocUserRoleMst;
     private MocWfStg mocWfStg;

    public MocWfStgRole() {
    }

	
    public MocWfStgRole(int id) {
        this.id = id;
    }
    public MocWfStgRole(int id, MocUserRoleMst mocUserRoleMst, MocWfStg mocWfStg) {
       this.id = id;
       this.mocUserRoleMst = mocUserRoleMst;
       this.mocWfStg = mocWfStg;
    }
   
    public int getId() {
        return this.id;
    }
    
    public void setId(int id) {
        this.id = id;
    }
    public MocUserRoleMst getMocUserRoleMst() {
        return this.mocUserRoleMst;
    }
    
    public void setMocUserRoleMst(MocUserRoleMst mocUserRoleMst) {
        this.mocUserRoleMst = mocUserRoleMst;
    }
    public MocWfStg getMocWfStg() {
        return this.mocWfStg;
    }
    
    public void setMocWfStg(MocWfStg mocWfStg) {
        this.mocWfStg = mocWfStg;
    }




}


