<%-- 
   Document   : dashboard
   Created on : Feb 19, 2015, 3:04:17 PM
   Author     : 02948
--%>
<%@page import="Dao.LoginDao"%>
<%@page import="Bean.LoginBean"%>
<%@page import="Dao.BillDao"%>
<%@page import="org.apache.jasper.tagplugins.jstl.core.ForEach"%>
<%@page import="Bean.WorkTermBean"%>
<%@page import="Bean.WorkItemBean"%>
<%@page import="Bean.WorkTaxBean"%>
<%@page import="java.util.ArrayList"%>
<%@page import="Bean.WorkBean"%>
<%@page import="Dao.WorkDao"%>

<%
    Logic.Dropdown.LoadDropdown();
    String bill1 = request.getParameter("bill");
    WorkBean wo1 = new WorkBean();
    ArrayList<WorkTaxBean> wt1 = new ArrayList<WorkTaxBean>();
    ArrayList<WorkItemBean> wi1 = new ArrayList<WorkItemBean>();
    WorkTermBean wp1 = new WorkTermBean();
    BillDao wdao1 = new BillDao();
    wo1 = wdao1.getBill(bill1);
    wi1 = wdao1.getBillItem(bill1);
    wt1 = wdao1.getBillTax(bill1);
    wp1 = wdao1.getBillTerm(bill1);
    ArrayList<WorkBean> billidlist = new ArrayList<WorkBean>();
    billidlist = wdao1.getBill_usr_no(wo1.getPO_NO());
%>
<!DOCTYPE html PUBLIC "-//W3C//DTD XHTML 1.0 Strict//EN" "http://www.w3.org/TR/xhtml1/DTD/xhtml1-strict.dtd">
<html xmlns="http://www.w3.org/1999/xhtml" xml:lang="en">
    <head>
        <meta http-equiv="Content-Type" content="text/html; charset=UTF-8"/>
        <title>Container DNLCBA</title>
        <link href="css/nav.css" type="text/css" rel="stylesheet"/>
        <link href="css/container.css" type="text/css" rel="stylesheet"/>
        <link href="css/dtb.css" type="text/css" rel="stylesheet"/>
        <script type="text/javascript" src="js/jquery-1.10.2.js"></script>
        <script type="text/javascript" src="js/jquery.min.js"></script>
        <script type="text/javascript" src="js/jquery.searchabledropdown-1.0.8.min.js"></script>
        <script src="js/Datepicker.js" type="text/javascript"></script>
        <link href="css/Datepicker.css" rel="stylesheet" type="text/css" />
        <script type="text/javascript">
            $(document).ready(function () {
                //DATE PICKER
                $("#k").datepicker({
                    showOn: 'button',
                    buttonText: 'Show Date',
                    buttonImageOnly: true,
                    buttonImage: 'image/calendar.gif',
                    dateFormat: 'mm/dd/yy',
                    constrainInput: true
                });
                //SELECT SEARCH
                $("select").searchable({
                    maxListSize: 200, // if list size are less than maxListSize, show them all
                    maxMultiMatch: 200, // how many matching entries should be displayed
                    exactMatch: false, // Exact matching on search
                    wildcards: true, // Support for wildcard characters (*, ?)
                    ignoreCase: true, // Ignore case sensitivity
                    latency: 200, // how many millis to wait until starting search
                    warnMultiMatch: 'top {0} matches ...', // string to append to a list of entries cut short by maxMultiMatch 
                    warnNoMatch: 'no matches ...', // string to show in the list when no entries match
                    zIndex: 'auto'// zIndex for elements generated by this plugin
                });

                var $submit = $('input[type="submit"]');
                $submit.prop('disabled', true);
            });
        </script>
    </head>
    <body>
        <%@include file="include/header.jsp" %>
        <div id="wrapper">
            <div id="Left">
                <%@include file="include/navbar.jsp" %>
            </div>
            <div id="Right">
                <div>
                    <h4 class="page_title">Update Bill</h4>
                </div>
                <form action="UpdateBill" method="post" onsubmit="submit.disabled = true;
                        submit.value = 'Processing ..';
                        return true;">
                    <fieldset>
                        <legend style="">Header</legend>
                        <%@include file="include/womstbu.jsp" %>
                    </fieldset>
                    <fieldset>
                        <legend>Item Detail</legend>
                        <%@include file="include/wodtbu.jsp" %>
                    </fieldset>
                    <fieldset>
                        <legend>Total Value and Terms</legend>
                        <%@include file="include/wofootbu.jsp" %>
                    </fieldset>
                    <fieldset style="background: #878D90">
                        <div style="font-size: large;color: #A70303;float: left;width: 300px" >
                            <%
                                ArrayList<LoginBean> ulist = new ArrayList<LoginBean>();
                                LoginDao ldao = new LoginDao();
                                ulist = ldao.getUserByRole("CRT");%>
                            <select id="NUID" name="NUID"  style="width: 250px" >  
                                <option value="">Select User For Approval</option>
                                <%  for (LoginBean lb : ulist) {%>
                                <option value="<%=lb.getUSER_ID()%>"><%=lb.getUSER_NAME()%></option>
                                <%}%>
                            </select>
                        </div>
                        <div style="float: left">
                            <span>Comment for approver</span>
                            <span style="color: red">*</span> <input type="text" value="" name="ucmt" id="ucmt" size="20"/>
                            <input type="submit" value="submit" id="submit" onclick="return validate();" name="submit" onsubmit="submit.disabled = true;
                                    submit.value = 'Processing ..';
                                    return true;"  />
                            <script>
                                var bills = [];
                                <%for (int i = 0; i < billidlist.size(); i++) {%>
                                bills.push("<%=billidlist.get(i).getBILL_ID().toUpperCase()%>");
                                <%}%>
                                bills.pop("<%=wo1.getBILL_ID().toUpperCase()%>");
                                function validate() {
                                    var bid = document.getElementById("bid").value;
                                    var k = document.getElementById("k").value;
                                    var itemrows = document.getElementById("itemrows").value;
                                    var NUID = document.getElementById("NUID");
                                    var valNUID = NUID.options[NUID.selectedIndex].value;
                                    var bool = "true";
                                    if (bid === "" || k === "") {
                                        alert("Please Fill Mandatory Fields : BillNumber and Bill Date ");
                                        bool = "false";
                                    }
                                    if (itemrows === "") {
                                        alert("Atleast one item should be selected");
                                        bool = "false";
                                    }
                                    if (valNUID === "") {
                                        alert("Please Select Next User for Approval");
                                        bool = "false";
                                    }
                                    for (i = 0; i < bills.length; i++) {
                                        if (bid === bills[i]) {
                                            alert("This Bill No is already used in system");
                                            bool = "false";
                                        }
                                    }
                                }
                            </script>
                    </fieldset> 
                </form>
            </div>
        </div>
        <%@include file="include/footer.jsp" %>
    </body>
</html>