package kp.beans.mst.pojo;
// Generated Nov 10, 2015 7:53:17 AM by Hibernate Tools 4.3.1



/**
 * MocPlantMst generated by hbm2java
 */
public class MocPlantMst  implements java.io.Serializable {


     private String plantId;
     private MocUnitMst mocUnitMst;
     private String plantName;

    public MocPlantMst() {
    }

	
    public MocPlantMst(String plantId) {
        this.plantId = plantId;
    }
    public MocPlantMst(String plantId, MocUnitMst mocUnitMst, String plantName) {
       this.plantId = plantId;
       this.mocUnitMst = mocUnitMst;
       this.plantName = plantName;
    }
   
    public String getPlantId() {
        return this.plantId;
    }
    
    public void setPlantId(String plantId) {
        this.plantId = plantId;
    }
    public MocUnitMst getMocUnitMst() {
        return this.mocUnitMst;
    }
    
    public void setMocUnitMst(MocUnitMst mocUnitMst) {
        this.mocUnitMst = mocUnitMst;
    }
    public String getPlantName() {
        return this.plantName;
    }
    
    public void setPlantName(String plantName) {
        this.plantName = plantName;
    }




}


