package kp.beans.mst.pojo;
// Generated Nov 10, 2015 7:53:17 AM by Hibernate Tools 4.3.1


import java.util.HashSet;
import java.util.Set;

/**
 * MocUnitMst generated by hbm2java
 */
public class MocUnitMst  implements java.io.Serializable {


     private String unitId;
     private String unitName;
     private Set mocPlantMsts = new HashSet(0);

    public MocUnitMst() {
    }

	
    public MocUnitMst(String unitId) {
        this.unitId = unitId;
    }
    public MocUnitMst(String unitId, String unitName, Set mocPlantMsts) {
       this.unitId = unitId;
       this.unitName = unitName;
       this.mocPlantMsts = mocPlantMsts;
    }
   
    public String getUnitId() {
        return this.unitId;
    }
    
    public void setUnitId(String unitId) {
        this.unitId = unitId;
    }
    public String getUnitName() {
        return this.unitName;
    }
    
    public void setUnitName(String unitName) {
        this.unitName = unitName;
    }
    public Set getMocPlantMsts() {
        return this.mocPlantMsts;
    }
    
    public void setMocPlantMsts(Set mocPlantMsts) {
        this.mocPlantMsts = mocPlantMsts;
    }




}


