$(document).ready(function () {
    //Show Loader
    $('#wrapper').loader('show');
    //Prevent Enter Submit
    $(window).keydown(function (event) {
        if (event.keyCode === 13) {
            event.preventDefault();
            return false;
        }
    });
    //Disable Submit button
    var $submit = $('input[type="submit"]');
    $submit.prop('disabled', true);
    //Date Picker
    $("#k").datepicker({
        showOn: 'button',
        buttonText: 'Show Date',
        buttonImageOnly: true,
        buttonImage: 'image/calendar.gif',
        dateFormat: 'mm/dd/yy',
        constrainInput: true
    });
//    $("#k").val($.datepicker.formatDate("mm/dd/yy", new Date()));
    $("#fk").datepicker({
        showOn: 'button',
        buttonText: 'Show Date',
        buttonImageOnly: true,
        buttonImage: 'image/calendar.gif',
        dateFormat: 'mm/dd/yy',
        constrainInput: true
    });
//    $("#fk").val($.datepicker.formatDate("mm/dd/yy", new Date()));
    //Search Select Box
    $("#A,#e,#T,#I").searchable({
        maxListSize: 1000, // if list size are less than maxListSize, show them all
        maxMultiMatch: 1000, // how many matching entries should be displayed
        exactMatch: false, // Exact matching on search
        wildcards: true, // Support for wildcard characters (*, ?)
        ignoreCase: true, // Ignore case sensitivity
        latency: 200, // how many millis to wait until starting search
        warnMultiMatch: 'top {0} matches ...', // string to append to a list of entries cut short by maxMultiMatch 
        warnNoMatch: 'no matches ...', // string to show in the list when no entries match
        zIndex: 'auto' // zIndex for elements generated by this plugin
    });
    $.ajax({
        cache: false
    });
    //Load DropDown
    $.get('ItemJson', {}, function (response) {
        var select = $('#A');
        select.find('option').remove();
        $.each(response, function (index, value) {
            $('<option>').val(index).text(value).appendTo(select);
        });
        //Close Loader
        $('#wrapper').loader('hide');
    });
    //Dropdown change event
    $('#A').change(function (event) {
        var item = $("select#A").val();
        var sup = $("select#e").val();
        $.get('ItemDtJson', {
            itemdt: item,
            supid: sup
        }, function (jsonResponse) {
            $.each(jsonResponse, function (index, value) {
                if (index === 0) {
                    $('#B').val(value);
                }
                if (index === 1) {
                    $('#C').val(value);
                }
                if (index === 2) {
                    $('#D').val(value);
                }
                if (index === 3) {
                    $('#E').val(value);
                }
                if (index === 4) {
                    $('#F').val(value);
                }
            });
        });
    });
    //Only Numbers Allowed
    $("#C,#D,#R,#i,#i2").keypress(function (e) {
        //if the letter is not digit then display error and don't type anything
        if (e.which !== 8 && e.which !== 0 && (e.which < 45 || e.which > 57)) {
            //display error message
            alert('Only Numbers Allowed');
            return false;
        }
    });
    //supplier dropdown change event
    $('#e').change(function (event) {
        var sup = $("select#e").val();
        $.get('SupDtJson', {
            sup: sup
        }, function (response) {
            var select = $('#f');
            select.find('option').remove();
            $.each(response, function (index, value) {
                var str = value;
                var n = str.indexOf("-");
                var van = str.substring(n + 1);
                $('<option>').val(van).text(value).appendTo(select);
            });
        });
    });
    //project dropdown change event
    $('#I').change(function (event) {
        var proj = $("select#I").val();
        $.get('TaskJson', {
            proj: proj
        }, function (response) {
            var select = $('#J');
            select.find('option').remove();
            $.each(response, function (index, value) {
                $('<option>').val(index).text(value).appendTo(select);
            });
        });
    });
    //default proj and task disabled
    var proj = $("select#I");
    var task = $("select#J");
    proj.attr('disabled', 'disabled');
    proj.addClass('readon');
    task.attr('disabled', 'disabled');
    task.addClass('readon');

    //work order type change
    $("#j").change(function () {
        var str = $("select#j").val();
        var proj = $("select#I");
        var task = $("select#J");
        if (str === 'Blanket') {
            proj.attr('disabled', 'disabled');
            proj.addClass('readon');
            task.attr('disabled', 'disabled');
            task.addClass('readon');
        } else {
            proj.removeAttr('disabled');
            proj.removeClass('readon');
            task.removeAttr('disabled');
            task.removeClass('readon');
        }
    });
});
function validate() {
    var vf = document.getElementById("fk").value;
    var vt = document.getElementById("k").value;
    var pot = document.getElementById("pot").value;
    var h = document.getElementById("pot").value;
    var e = document.getElementById("e");
    var val = e.options[e.selectedIndex].value;
    var PT = document.getElementById("PT");
    var valPT = PT.options[PT.selectedIndex].value;
    var txrows = document.getElementById("txrows").value;
    var itemrows = document.getElementById("itemrows").value;
    if (pot === "" || val === "" || h === "" || valPT === "0" || txrows === "" || itemrows === "" || vf === "" || vt === "") {
        alert("Please Fill Mandatory Fields : Title , Supplier , Payment Term,Vlid From and To date ");
        if (txrows === "" || itemrows === "") {
            alert("Please Fill Mandatory Fields : Tax Line , Item Line");
        }
        return false;
    }
}