package kp.beans.data.pojo;
// Generated Nov 10, 2015 7:53:17 AM by Hibernate Tools 4.3.1

import kp.logic.GeneralMethods;

/**
 * MocInitPip generated by hbm2java
 */
public class MocInitPip implements java.io.Serializable {

    private GeneralMethods gm = new GeneralMethods();

    private int caseId;
    private String d1;
    private String d2;
    private String d3;
    private String d4;
    private String d5;
    private String d6;
    private String d7;
    private MocInitMst mocInitMst;

    public MocInitPip() {
        d1 = "";
        d2 = "";
        d3 = "";
        d4 = "";
        d5 = "";
        d6 = "";
        d7 = "";
        mocInitMst = null;
    }

    public MocInitPip(int caseId) {
        this.caseId = caseId;
    }

    public MocInitPip(int caseId, String d1, String d2, String d3, String d4, String d5, String d6, String d7, MocInitMst mocInitMst) {
        this.caseId = caseId;
        this.d1 = d1;
        this.d2 = d2;
        this.d3 = d3;
        this.d4 = d4;
        this.d5 = d5;
        this.d6 = d6;
        this.d7 = d7;
        this.mocInitMst = mocInitMst;
    }

    public String getD1() {
        return gm.getCheckStatus(this.d1);
    }

    public void setD1(String d1) {
        this.d1 = d1;
    }

    public String getD2() {
        return gm.getCheckStatus(this.d2);
    }

    public void setD2(String d2) {
        this.d2 = d2;
    }

    public String getD3() {
        return gm.getCheckStatus(this.d3);
    }

    public void setD3(String d3) {
        this.d3 = d3;
    }

    public String getD4() {
        return gm.getCheckStatus(this.d4);
    }

    public void setD4(String d4) {
        this.d4 = d4;
    }

    public String getD5() {
        return gm.getCheckStatus(this.d5);
    }

    public void setD5(String d5) {
        this.d5 = d5;
    }

    public String getD6() {
        return gm.getCheckStatus(this.d6);
    }

    public void setD6(String d6) {
        this.d6 = d6;
    }

    public String getD7() {
        return this.d7;
    }

    public void setD7(String d7) {
        this.d7 = d7;
    }

    /**
     * @return the caseId
     */
    public int getCaseId() {
        return caseId;
    }

    /**
     * @param caseId the caseId to set
     */
    public void setCaseId(int caseId) {
        this.caseId = caseId;
    }

    /**
     * @return the MocInitMst
     */
    public MocInitMst getMocInitMst() {
        return mocInitMst;
    }

    /**
     * @param MocInitMst the MocInitMst to set
     */
    public void setMocInitMst(MocInitMst mocInitMst) {
        this.mocInitMst = mocInitMst;
    }

}
