package kp.beans.data.pojo;
// Generated Nov 10, 2015 7:53:17 AM by Hibernate Tools 4.3.1

import kp.logic.GeneralMethods;

/**
 * MocInitProc generated by hbm2java
 */
public class MocInitProc implements java.io.Serializable {

    private GeneralMethods gm = new GeneralMethods();

    private int caseId;
    private String g1;
    private String g2;
    private String g3;
    private String g4;
    private String g5;
    private String g6;
    private String g7;
    private String g8;
    private String g9;
    private String g10;
    private String g11;
    private String g12;
    private String g13;
    private String g14;
    private String g15;
    private String g16;
    private String g17;
    private String g18;
    private String g19;
    private String g20;
    private String g21;
    private String g22;
    private String g23;
    private String g24;
    private String g25;
    private String g26;
    private String g27;
    private MocInitMst mocInitMst;

    public MocInitProc() {

        g1 = "";
        g2 = "";
        g3 = "";
        g4 = "";
        g5 = "";
        g6 = "";
        g7 = "";
        g8 = "";
        g9 = "";
        g10 = "";
        g11 = "";
        g12 = "";
        g13 = "";
        g14 = "";
        g15 = "";
        g16 = "";
        g17 = "";
        g18 = "";
        g19 = "";
        g20 = "";
        g21 = "";
        g22 = "";
        g23 = "";
        g24 = "";
        g25 = "";
        g26 = "";
        g27 = "";
        mocInitMst = null;
    }

    public MocInitProc(int caseId) {
        this.caseId = caseId;
    }

    public MocInitProc(int caseId, String g1, String g2, String g3, String g4, String g5, String g6, String g7, String g8, String g9, String g10, String g11, String g12, String g13, String g14, String g15, String g16, String g17, String g18, String g19, String g20, String g21, String g22, String g23, String g24, String g25, String g26, String g27, MocInitMst mocInitMst) {
        this.caseId = caseId;
        this.g1 = g1;
        this.g2 = g2;
        this.g3 = g3;
        this.g4 = g4;
        this.g5 = g5;
        this.g6 = g6;
        this.g7 = g7;
        this.g8 = g8;
        this.g9 = g9;
        this.g10 = g10;
        this.g11 = g11;
        this.g12 = g12;
        this.g13 = g13;
        this.g14 = g14;
        this.g15 = g15;
        this.g16 = g16;
        this.g17 = g17;
        this.g18 = g18;
        this.g19 = g19;
        this.g20 = g20;
        this.g21 = g21;
        this.g22 = g22;
        this.g23 = g23;
        this.g24 = g24;
        this.g25 = g25;
        this.g26 = g26;
        this.g27 = g27;
        this.mocInitMst = mocInitMst;
    }

    public String getG1() {
        return gm.getCheckStatus(this.g1);
    }

    public void setG1(String g1) {
        this.g1 = g1;
    }

    public String getG2() {
        return gm.getCheckStatus(this.g2);
    }

    public void setG2(String g2) {
        this.g2 = g2;
    }

    public String getG3() {
        return gm.getCheckStatus(this.g3);
    }

    public void setG3(String g3) {
        this.g3 = g3;
    }

    public String getG4() {
        return gm.getCheckStatus(this.g4);
    }

    public void setG4(String g4) {
        this.g4 = g4;
    }

    public String getG5() {
        return gm.getCheckStatus(this.g5);
    }

    public void setG5(String g5) {
        this.g5 = g5;
    }

    public String getG6() {
        return gm.getCheckStatus(this.g6);
    }

    public void setG6(String g6) {
        this.g6 = g6;
    }

    public String getG7() {
        return gm.getCheckStatus(this.g7);
    }

    public void setG7(String g7) {
        this.g7 = g7;
    }

    public String getG8() {
        return gm.getCheckStatus(this.g8);

    }

    public void setG8(String g8) {
        this.g8 = g8;
    }

    public String getG9() {
        return gm.getCheckStatus(this.g9);
    }

    public void setG9(String g9) {
        this.g9 = g9;
    }

    public String getG10() {
        return gm.getCheckStatus(this.g10);
    }

    public void setG10(String g10) {
        this.g10 = g10;
    }

    public String getG11() {
        return gm.getCheckStatus(this.g11);
    }

    public void setG11(String g11) {
        this.g11 = g11;
    }

    public String getG12() {
        return gm.getCheckStatus(this.g12);
    }

    public void setG12(String g12) {
        this.g12 = g12;
    }

    public String getG13() {
        return gm.getCheckStatus(this.g13);
    }

    public void setG13(String g13) {
        this.g13 = g13;
    }

    public String getG14() {
        return gm.getCheckStatus(this.g14);
    }

    public void setG14(String g14) {
        this.g14 = g14;
    }

    public String getG15() {
        return gm.getCheckStatus(this.g15);
    }

    public void setG15(String g15) {
        this.g15 = g15;
    }

    public String getG16() {
        return gm.getCheckStatus(this.g16);
    }

    public void setG16(String g16) {
        this.g16 = g16;
    }

    public String getG17() {
        return gm.getCheckStatus(this.g17);
    }

    public void setG17(String g17) {
        this.g17 = g17;
    }

    public String getG18() {
        return gm.getCheckStatus(this.g18);
    }

    public void setG18(String g18) {
        this.g18 = g18;
    }

    public String getG19() {
        return gm.getCheckStatus(this.g19);
    }

    public void setG19(String g19) {
        this.g19 = g19;
    }

    public String getG20() {
        return gm.getCheckStatus(this.g20);
    }

    public void setG20(String g20) {
        this.g20 = g20;
    }

    public String getG21() {
        return gm.getCheckStatus(this.g21);
    }

    public void setG21(String g21) {
        this.g21 = g21;
    }

    public String getG22() {
        return gm.getCheckStatus(this.g22);
    }

    public void setG22(String g22) {
        this.g22 = g22;
    }

    public String getG23() {
        return gm.getCheckStatus(this.g23);
    }

    public void setG23(String g23) {
        this.g23 = g23;
    }

    public String getG24() {
        return gm.getCheckStatus(this.g24);
    }

    public void setG24(String g24) {
        this.g24 = g24;
    }

    public String getG25() {
        return gm.getCheckStatus(this.g25);
    }

    public void setG25(String g25) {
        this.g25 = g25;
    }

    public String getG26() {
        return gm.getCheckStatus(this.g26);
    }

    public void setG26(String g26) {
        this.g26 = g26;
    }

    public String getG27() {
        return this.g27;
    }

    public void setG27(String g27) {
        this.g27 = g27;
    }

    /**
     * @return the caseId
     */
    public int getCaseId() {
        return caseId;
    }

    /**
     * @param caseId the caseId to set
     */
    public void setCaseId(int caseId) {
        this.caseId = caseId;
    }

    /**
     * @return the MocInitMst
     */
    public MocInitMst getMocInitMst() {
        return mocInitMst;
    }

    /**
     * @param MocInitMst the MocInitMst to set
     */
    public void setMocInitMst(MocInitMst mocInitMst) {
        this.mocInitMst = mocInitMst;
    }

}
