package kp.beans.data.pojo;
// Generated Nov 10, 2015 7:53:17 AM by Hibernate Tools 4.3.1

import java.util.Date;
import kp.logic.GeneralMethods;

/**
 * MocInitTskDt generated by hbm2java
 */
public class MocInitTskDt implements java.io.Serializable {

    private GeneralMethods gm = new GeneralMethods();
    private int id;
    private MocInitMst mocInitMst;
    private int docId;
    private String docName;
    private String up;
    private String resParty;
    private String resPartyName;
    private Date tarDate;
    private String tarDateString;
    private Date comDate;
    private String comDateString;

    public MocInitTskDt() {
        mocInitMst = null;
        docId = 0;
        up = "";
        resParty = "";
        tarDate = null;
        comDate = null;
    }

    public MocInitTskDt(int id) {
        this.id = id;
    }

    public MocInitTskDt(int id, MocInitMst mocInitMst, int docId, String up, String resParty, Date tarDate, Date comDate) {
        this.id = id;
        this.mocInitMst = mocInitMst;
        this.docId = docId;
        this.up = up;
        this.resParty = resParty;
        this.tarDate = tarDate;
        this.comDate = comDate;
    }

    public int getId() {
        return this.id;
    }

    public void setId(int id) {
        this.id = id;
    }

    public MocInitMst getMocInitMst() {
        return this.mocInitMst;
    }

    public void setMocInitMst(MocInitMst mocInitMst) {
        this.mocInitMst = mocInitMst;
    }

    public int getDocId() {
        return this.docId;
    }

    public void setDocId(int docId) {
        this.docId = docId;
    }

    public String getUp() {
        return getGm().getCheckStatus(this.up);
    }

    public void setUp(String up) {
        this.up = up;
    }

    public String getResParty() {
        return this.resParty;
    }

    public void setResParty(String resParty) {
        this.resParty = resParty;
    }

    public Date getTarDate() {
        return this.tarDate;
    }

    public void setTarDate(Date tarDate) {
        this.tarDate = tarDate;
    }

    public Date getComDate() {
        return this.comDate;
    }

    public void setComDate(Date comDate) {
        this.comDate = comDate;
    }

    /**
     * @return the gm
     */
    public GeneralMethods getGm() {
        return gm;
    }

    /**
     * @param gm the gm to set
     */
    public void setGm(GeneralMethods gm) {
        this.gm = gm;
    }

    /**
     * @return the docName
     */
    public String getDocName() {
        return docName;
    }

    /**
     * @param docName the docName to set
     */
    public void setDocName(String docName) {
        this.docName = docName;
    }

    /**
     * @return the resPartyName
     */
    public String getResPartyName() {
        return resPartyName;
    }

    /**
     * @param resPartyName the resPartyName to set
     */
    public void setResPartyName(String resPartyName) {
        this.resPartyName = resPartyName;
    }

    /**
     * @return the tarDateString
     */
    public String getTarDateString() {
        return tarDateString;
    }

    /**
     * @param tarDateString the tarDateString to set
     */
    public void setTarDateString(String tarDateString) {
        this.tarDateString = tarDateString;
    }

    /**
     * @return the comDateString
     */
    public String getComDateString() {
        return comDateString;
    }

    /**
     * @param comDateString the comDateString to set
     */
    public void setComDateString(String comDateString) {
        this.comDateString = comDateString;
    }

}
