package kp.beans.data.pojo;
// Generated Nov 10, 2015 7:53:17 AM by Hibernate Tools 4.3.1

import java.util.Date;
import java.util.HashSet;
import java.util.Set;

/**
 * MocInitMst generated by hbm2java
 */
public class MocInitMst implements java.io.Serializable {

    private int caseId;
    private MocInitReq mocInitReq;
    private MocInitSta mocInitSta;
    private MocInitRot mocInitRot;
    private MocInitPip mocInitPip;
    private MocInitEle mocInitEle;
    private MocInitProd mocInitProd;
    private MocInitProc mocInitProc;
    private MocInitPseq mocInitPseq;
    private String userId;
    private Date crDate;
    private String mocNo;
    private String status;
    private String unitId;
    private Date appDate;
    private MocTsMst mocTsMst;
    private MocHseMst mocSheMst;
    private MocQcMst mocQcMst;
    private Set mocInitTskDts = new HashSet(0);
    private Set mocEngMsts = new HashSet(0);
    private Set mocWfTran = new HashSet(0);
    private Set mocWfUser = new HashSet(0);
    private MocEngMst mocEngMst;

    public MocInitMst() {
        mocInitReq = null;
        mocInitSta = null;
        mocInitRot = null;
        mocInitPip = null;
        mocInitEle = null;
        mocInitProd = null;
        mocInitProc = null;
        mocInitPseq = null;
        userId = "";
        crDate = null;
        mocNo = "";
        unitId = "";
        appDate = null;
        mocTsMst = null;
        mocInitTskDts = null;
        mocSheMst = null;
        mocQcMst = null;
        mocEngMsts = null;
        mocWfUser = null;
    }

    public MocInitMst(int caseId, MocInitReq mocInitReq, MocInitSta mocInitSta, MocInitRot mocInitRot, MocInitPip mocInitPip, MocInitEle mocInitEle, MocInitProd mocInitProd, MocInitProc mocInitProc, MocInitPseq mocInitPseq, String unitId) {
        this.caseId = caseId;
        this.mocInitReq = mocInitReq;
        this.mocInitSta = mocInitSta;
        this.mocInitRot = mocInitRot;
        this.mocInitPip = mocInitPip;
        this.mocInitEle = mocInitEle;
        this.mocInitProd = mocInitProd;
        this.mocInitProc = mocInitProc;
        this.mocInitPseq = mocInitPseq;
        this.unitId = unitId;
    }

    public MocInitMst(int caseId, MocInitReq mocInitReq, MocInitSta mocInitSta, MocInitRot mocInitRot,
            MocInitPip mocInitPip, MocInitEle mocInitEle, MocInitProd mocInitProd, MocInitProc mocInitProc,
            MocInitPseq mocInitPseq, String userId, Date crDate, String mocNo, String unitId, Date appDate,
            MocTsMst mocTsMst, MocHseMst mocSheMst, MocQcMst mocQcMst, Set mocEngMsts, Set mocInitTskDts) {
        this.caseId = caseId;
        this.mocInitReq = mocInitReq;
        this.mocInitSta = mocInitSta;
        this.mocInitRot = mocInitRot;
        this.mocInitPip = mocInitPip;
        this.mocInitEle = mocInitEle;
        this.mocInitProd = mocInitProd;
        this.mocInitProc = mocInitProc;
        this.mocInitPseq = mocInitPseq;
        this.userId = userId;
        this.crDate = crDate;
        this.mocNo = mocNo;
        this.unitId = unitId;
        this.appDate = appDate;
        this.mocTsMst = mocTsMst;
        this.mocInitTskDts = mocInitTskDts;
        this.mocSheMst = mocSheMst;
        this.mocQcMst = mocQcMst;
    }

    public int getCaseId() {
        return this.caseId;
    }

    public void setCaseId(int caseId) {
        this.caseId = caseId;
    }

    public MocInitReq getMocInitReq() {
        return this.mocInitReq;
    }

    public void setMocInitReq(MocInitReq mocInitReq) {
        this.mocInitReq = mocInitReq;
    }

    public MocInitSta getMocInitSta() {
        return this.mocInitSta;
    }

    public void setMocInitSta(MocInitSta mocInitSta) {
        this.mocInitSta = mocInitSta;
    }

    public MocInitRot getMocInitRot() {
        return this.mocInitRot;
    }

    public void setMocInitRot(MocInitRot mocInitRot) {
        this.mocInitRot = mocInitRot;
    }

    public MocInitPip getMocInitPip() {
        return this.mocInitPip;
    }

    public void setMocInitPip(MocInitPip mocInitPip) {
        this.mocInitPip = mocInitPip;
    }

    public MocInitEle getMocInitEle() {
        return this.mocInitEle;
    }

    public void setMocInitEle(MocInitEle mocInitEle) {
        this.mocInitEle = mocInitEle;
    }

    public MocInitProd getMocInitProd() {
        return this.mocInitProd;
    }

    public void setMocInitProd(MocInitProd mocInitProd) {
        this.mocInitProd = mocInitProd;
    }

    public MocInitProc getMocInitProc() {
        return this.mocInitProc;
    }

    public void setMocInitProc(MocInitProc mocInitProc) {
        this.mocInitProc = mocInitProc;
    }

    public MocInitPseq getMocInitPseq() {
        return this.mocInitPseq;
    }

    public void setMocInitPseq(MocInitPseq mocInitPseq) {
        this.mocInitPseq = mocInitPseq;
    }

    public String getUserId() {
        return this.userId;
    }

    public void setUserId(String userId) {
        this.userId = userId;
    }

    public Date getCrDate() {
        return this.crDate;
    }

    public void setCrDate(Date crDate) {
        this.crDate = crDate;
    }

    public String getMocNo() {
        return this.mocNo;
    }

    public void setMocNo(String mocNo) {
        this.mocNo = mocNo;
    }

    public String getUnitId() {
        return this.unitId;
    }

    public void setUnitId(String unitId) {
        this.unitId = unitId;
    }

    public Date getAppDate() {
        return this.appDate;
    }

    public void setAppDate(Date appDate) {
        this.appDate = appDate;
    }

    public Set getMocInitTskDts() {
        return this.mocInitTskDts;
    }

    public void setMocInitTskDts(Set mocInitTskDts) {
        this.mocInitTskDts = mocInitTskDts;
    }

    /**
     * @return the status
     */
    public String getStatus() {
        return status;
    }

    /**
     * @param status the status to set
     */
    public void setStatus(String status) {
        this.status = status;
    }

    /**
     * @return the mocTsMst
     */
    public MocTsMst getMocTsMst() {
        return mocTsMst;
    }

    /**
     * @param mocTsMst the mocTsMst to set
     */
    public void setMocTsMst(MocTsMst mocTsMst) {
        this.mocTsMst = mocTsMst;
    }

    /**
     * @return the mocSheMst
     */
    public MocHseMst getMocSheMst() {
        return mocSheMst;
    }

    /**
     * @param mocSheMst the mocSheMst to set
     */
    public void setMocSheMst(MocHseMst mocSheMst) {
        this.mocSheMst = mocSheMst;
    }

    /**
     * @return the mocQcMst
     */
    public MocQcMst getMocQcMst() {
        return mocQcMst;
    }

    /**
     * @param mocQcMst the mocQcMst to set
     */
    public void setMocQcMst(MocQcMst mocQcMst) {
        this.mocQcMst = mocQcMst;
    }

    /**
     * @return the mocWfTran
     */
    public Set getMocWfTran() {
        return mocWfTran;
    }

    /**
     * @param mocWfTran the mocWfTran to set
     */
    public void setMocWfTran(Set mocWfTran) {
        this.mocWfTran = mocWfTran;
    }

    /**
     * @return the mocEngMsts
     */
    public Set getMocEngMsts() {
        return mocEngMsts;
    }

    /**
     * @param mocEngMsts the mocEngMsts to set
     */
    public void setMocEngMsts(Set mocEngMsts) {
        this.mocEngMsts = mocEngMsts;
    }

    /**
     * @return the mocEngMst
     */
    public MocEngMst getMocEngMst() {
        return mocEngMst;
    }

    /**
     * @param mocEngMst the mocEngMst to set
     */
    public void setMocEngMst(MocEngMst mocEngMst) {
        this.mocEngMst = mocEngMst;
    }

    /**
     * @return the mocWfUser
     */
    public Set getMocWfUser() {
        return mocWfUser;
    }

    /**
     * @param mocWfUser the mocWfUser to set
     */
    public void setMocWfUser(Set mocWfUser) {
        this.mocWfUser = mocWfUser;
    }
}
