package kp.beans.data.pojo;
// Generated Nov 10, 2015 7:53:17 AM by Hibernate Tools 4.3.1

import kp.logic.GeneralMethods;

/**
 * MocInitEle generated by hbm2java
 */
public class MocInitEle implements java.io.Serializable {

    private GeneralMethods gm = new GeneralMethods();

    private int caseId;
    private String e1;
    private String e2;
    private String e3;
    private String e4;
    private String e5;
    private String e6;
    private String e7;
    private MocInitMst mocInitMst;

    public MocInitEle() {
        e1 = "";
        e2 = "";
        e3 = "";
        e4 = "";
        e5 = "";
        e6 = "";
        e7 = "";
        mocInitMst = null;
    }

    public MocInitEle(int caseId) {
        this.caseId = caseId;
    }

    public MocInitEle(int caseId, String e1, String e2, String e3, String e4, String e5, String e6, String e7, MocInitMst mocInitMst) {
        this.caseId = caseId;
        this.e1 = e1;
        this.e2 = e2;
        this.e3 = e3;
        this.e4 = e4;
        this.e5 = e5;
        this.e6 = e6;
        this.e7 = e7;
        this.mocInitMst = mocInitMst;
    }

    public String getE1() {
        return gm.getCheckStatus(this.e1);
    }

    public void setE1(String e1) {
        this.e1 = e1;
    }

    public String getE2() {
        return gm.getCheckStatus(this.e2);
    }

    public void setE2(String e2) {
        this.e2 = e2;
    }

    public String getE3() {
        return gm.getCheckStatus(this.e3);
    }

    public void setE3(String e3) {
        this.e3 = e3;
    }

    public String getE4() {
        return gm.getCheckStatus(this.e4);
    }

    public void setE4(String e4) {
        this.e4 = e4;
    }

    public String getE5() {
        return gm.getCheckStatus(this.e5);
    }

    public void setE5(String e5) {
        this.e5 = e5;
    }

    public String getE6() {
        return gm.getCheckStatus(this.e6);
    }

    public void setE6(String e6) {
        this.e6 = e6;
    }

    public String getE7() {
        return this.e7;
    }

    public void setE7(String e7) {
        this.e7 = e7;
    }

    /**
     * @return the caseId
     */
    public int getCaseId() {
        return caseId;
    }

    /**
     * @param caseId the caseId to set
     */
    public void setCaseId(int caseId) {
        this.caseId = caseId;
    }

    /**
     * @return the mocInitMst
     */
    public MocInitMst getMocInitMst() {
        return mocInitMst;
    }

    /**
     * @param mocInitMst the mocInitMst to set
     */
    public void setMocInitMst(MocInitMst mocInitMst) {
        this.mocInitMst = mocInitMst;
    }

}
