package kp.beans.data.pojo;
// Generated Nov 10, 2015 7:53:17 AM by Hibernate Tools 4.3.1

import kp.logic.GeneralMethods;

/**
 * MocInitProd generated by hbm2java
 */
public class MocInitProd implements java.io.Serializable {

    private GeneralMethods gm = new GeneralMethods();

    private int caseId;
    private String f1;
    private String f2;
    private String f3;
    private String f4;
    private String f5;
    private String f6;
    private MocInitMst mocInitMst;

    public MocInitProd() {
        f1 = "";
        f2 = "";
        f3 = "";
        f4 = "";
        f5 = "";
        f6 = "";
        mocInitMst = null;
    }

    public MocInitProd(int caseId) {
        this.caseId = caseId;
    }

    public MocInitProd(int caseId, String f1, String f2, String f3, String f4, String f5, String f6, MocInitMst mocInitMst) {
        this.caseId = caseId;
        this.f1 = f1;
        this.f2 = f2;
        this.f3 = f3;
        this.f4 = f4;
        this.f5 = f5;
        this.f6 = f6;
        this.mocInitMst = mocInitMst;
    }

    public String getF1() {
        return gm.getCheckStatus(this.f1);
    }

    public void setF1(String f1) {
        this.f1 = f1;
    }

    public String getF2() {
        return gm.getCheckStatus(this.f2);
    }

    public void setF2(String f2) {
        this.f2 = f2;
    }

    public String getF3() {
        return gm.getCheckStatus(this.f3);
    }

    public void setF3(String f3) {
        this.f3 = f3;
    }

    public String getF4() {
        return gm.getCheckStatus(this.f4);
    }

    public void setF4(String f4) {
        this.f4 = f4;
    }

    public String getF5() {
        return gm.getCheckStatus(this.f5);
    }

    public void setF5(String f5) {
        this.f5 = f5;
    }

    public String getF6() {
        return this.f6;
    }

    public void setF6(String f6) {
        this.f6 = f6;
    }

    /**
     * @return the caseId
     */
    public int getCaseId() {
        return caseId;
    }

    /**
     * @param caseId the caseId to set
     */
    public void setCaseId(int caseId) {
        this.caseId = caseId;
    }

    /**
     * @return the MocInitMst
     */
    public MocInitMst getMocInitMst() {
        return mocInitMst;
    }

    /**
     * @param MocInitMst the MocInitMst to set
     */
    public void setMocInitMst(MocInitMst mocInitMst) {
        this.mocInitMst = mocInitMst;
    }

}
