package kp.beans.data.pojo;
// Generated Nov 10, 2015 7:53:17 AM by Hibernate Tools 4.3.1

import kp.logic.GeneralMethods;

/**
 * MocInitSta generated by hbm2java
 */
public class MocInitSta implements java.io.Serializable {

    private GeneralMethods gm = new GeneralMethods();

    private int caseId;
    private String b1;
    private String b2;
    private String b3;
    private String b4;
    private String b5;
    private String b6;
    private String b7;
    private String b8;
    private String b9;
    private String b10;
    private String b11;
    private String b12;
    private String b13;
    private String b14;
    private String b15;
    private String b16;
    private String b17;
    private MocInitMst mocInitMst;

    public MocInitSta() {
        b1 = "";
        b2 = "";
        b3 = "";
        b4 = "";
        b5 = "";
        b6 = "";
        b7 = "";
        b8 = "";
        b9 = "";
        b10 = "";
        b11 = "";
        b12 = "";
        b13 = "";
        b14 = "";
        b15 = "";
        b16 = "";
        b17 = "";
        mocInitMst = null;
    }

    public MocInitSta(int caseId) {
        this.caseId = caseId;
    }

    public MocInitSta(int id, String b1, String b2, String b3, String b4, String b5, String b6, String b7, String b8, String b9, String b10, String b11, String b12, String b13, String b14, String b15, String b16, String b17, MocInitMst mocInitMst) {
        this.caseId = id;
        this.b1 = b1;
        this.b2 = b2;
        this.b3 = b3;
        this.b4 = b4;
        this.b5 = b5;
        this.b6 = b6;
        this.b7 = b7;
        this.b8 = b8;
        this.b9 = b9;
        this.b10 = b10;
        this.b11 = b11;
        this.b12 = b12;
        this.b13 = b13;
        this.b14 = b14;
        this.b15 = b15;
        this.b16 = b16;
        this.b17 = b17;
        this.mocInitMst = mocInitMst;
    }

    public String getB1() {
        return gm.getCheckStatus(this.b1);
    }

    public void setB1(String b1) {
        this.b1 = b1;
    }

    public String getB2() {
        return gm.getCheckStatus(this.b2);
    }

    public void setB2(String b2) {
        this.b2 = b2;
    }

    public String getB3() {
        return gm.getCheckStatus(this.b3);
    }

    public void setB3(String b3) {
        this.b3 = b3;
    }

    public String getB4() {
        return gm.getCheckStatus(this.b4);
    }

    public void setB4(String b4) {
        this.b4 = b4;
    }

    public String getB5() {
        return gm.getCheckStatus(this.b5);
    }

    public void setB5(String b5) {
        this.b5 = b5;
    }

    public String getB6() {
        return this.b6;
    }

    public void setB6(String b6) {
        this.b6 = b6;
    }

    public String getB7() {
        return gm.getCheckStatus(this.b7);
    }

    public void setB7(String b7) {
        this.b7 = b7;
    }

    public String getB8() {
        return gm.getCheckStatus(this.b8);
    }

    public void setB8(String b8) {
        this.b8 = b8;
    }

    public String getB9() {
        return gm.getCheckStatus(this.b9);
    }

    public void setB9(String b9) {
        this.b9 = b9;
    }

    public String getB10() {
        return gm.getCheckStatus(this.b10);
    }

    public void setB10(String b10) {
        this.b10 = b10;
    }

    public String getB11() {
        return gm.getCheckStatus(this.b11);
    }

    public void setB11(String b11) {
        this.b11 = b11;
    }

    public String getB12() {
        return gm.getCheckStatus(this.b12);
    }

    public void setB12(String b12) {
        this.b12 = b12;
    }

    public String getB13() {
        return gm.getCheckStatus(this.b13);
    }

    public void setB13(String b13) {
        this.b13 = b13;
    }

    public String getB14() {
        return gm.getCheckStatus(this.b14);
    }

    public void setB14(String b14) {
        this.b14 = b14;
    }

    public String getB15() {
        return gm.getCheckStatus(this.b15);
    }

    public void setB15(String b15) {
        this.b15 = b15;
    }

    public String getB16() {
        return gm.getCheckStatus(this.b16);
    }

    public void setB16(String b16) {
        this.b16 = b16;
    }

    public String getB17() {
        return this.b17;
    }

    public void setB17(String b17) {
        this.b17 = b17;
    }

    /**
     * @return the caseId
     */
    public int getCaseId() {
        return caseId;
    }

    /**
     * @param caseId the caseId to set
     */
    public void setCaseId(int caseId) {
        this.caseId = caseId;
    }

    /**
     * @return the MocInitMst
     */
    public MocInitMst getMocInitMst() {
        return mocInitMst;
    }

    /**
     * @param MocInitMst the MocInitMst to set
     */
    public void setMocInitMst(MocInitMst mocInitMst) {
        this.mocInitMst = mocInitMst;
    }

}
