package kp.beans.data.pojo;
// Generated Nov 10, 2015 7:53:17 AM by Hibernate Tools 4.3.1

import java.util.Date;

/**
 * MocQcMst generated by hbm2java
 */
public class MocQcMst implements java.io.Serializable {

    private int caseId;
    private MocInitMst mocInitMst;
    private String userId;
    private Date actDate;
    private String k1;
    private String k2;

    public MocQcMst() {
        caseId = 0;
        mocInitMst = null;
        userId = "";
        actDate = null;
        k1 = "";
        k2 = "";
    }

    public MocQcMst(int caseId) {
        this.caseId = caseId;
    }

    public MocQcMst(int caseId, MocInitMst mocInitMst, String userId, Date actDate, String k1, String k2) {
        this.caseId = caseId;
        this.mocInitMst = mocInitMst;
        this.userId = userId;
        this.actDate = actDate;
        this.k1 = k1;
        this.k2 = k2;
    }

    public MocInitMst getMocInitMst() {
        return this.mocInitMst;
    }

    public void setMocInitMst(MocInitMst mocInitMst) {
        this.mocInitMst = mocInitMst;
    }

    public String getUserId() {
        return this.userId;
    }

    public void setUserId(String userId) {
        this.userId = userId;
    }

    public Date getActDate() {
        return this.actDate;
    }

    public void setActDate(Date actDate) {
        this.actDate = actDate;
    }

    public String getK1() {
        return this.k1;
    }

    public void setK1(String k1) {
        this.k1 = k1;
    }

    public String getK2() {
        return this.k2;
    }

    public void setK2(String k2) {
        this.k2 = k2;
    }

    /**
     * @return the caseId
     */
    public int getCaseId() {
        return caseId;
    }

    /**
     * @param caseId the caseId to set
     */
    public void setCaseId(int caseId) {
        this.caseId = caseId;
    }

}
