package kp.beans.data.pojo;
// Generated Nov 10, 2015 7:53:17 AM by Hibernate Tools 4.3.1

import java.util.Date;
import kp.logic.GeneralMethods;

/**
 * MocTsMst generated by hbm2java
 */
public class MocTsMst implements java.io.Serializable {

    private GeneralMethods gm = new GeneralMethods();

    private int caseId;
    private MocInitMst mocInitMst;
    private String userId;
    private Date actDate;
    private String i1;
    private String i2;
    private String i3;
    private String i4;

    public MocTsMst() {
        caseId = 0;
        userId = "";
        actDate = null;
        i1 = "";
        i2 = "";
        i3 = "";
        i4 = "";
        mocInitMst = null;
    }

    public MocTsMst(int caseId) {
        this.caseId = caseId;
    }

    public MocTsMst(int tsId, MocInitMst mocInitMst, String userId, Date actDate, String i1, String i2, String i3, String i4) {
        this.caseId = caseId;
        this.mocInitMst = mocInitMst;
        this.userId = userId;
        this.actDate = actDate;
        this.i1 = i1;
        this.i2 = i2;
        this.i3 = i3;
        this.i4 = i4;
    }

    public MocInitMst getMocInitMst() {
        return this.mocInitMst;
    }

    public void setMocInitMst(MocInitMst mocInitMst) {
        this.mocInitMst = mocInitMst;
    }

    public String getUserId() {
        return this.userId;
    }

    public void setUserId(String userId) {
        this.userId = userId;
    }

    public Date getActDate() {
        return this.actDate;
    }

    public void setActDate(Date actDate) {
        this.actDate = actDate;
    }

    public String getI1() {
        return gm.getCheckStatus(this.i1);
    }

    public void setI1(String i1) {
        this.i1 = i1;
    }

    public String getI2() {
        return gm.getCheckStatus(this.i2);
    }

    public void setI2(String i2) {
        this.i2 = i2;
    }

    public String getI3() {
        return this.i3;
    }

    public void setI3(String i3) {
        this.i3 = i3;
    }

    public String getI4() {
        return gm.getCheckStatus(this.i4);
    }

    public void setI4(String i4) {
        this.i4 = i4;
    }

    /**
     * @return the caseId
     */
    public int getCaseId() {
        return caseId;
    }

    /**
     * @param caseId the caseId to set
     */
    public void setCaseId(int caseId) {
        this.caseId = caseId;
    }

}
